spring:
  application:
    name: notificacao-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notificacao}${DB_URL_PARAM:?ssl=false}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: javafiapgrupo29@gmail.com
    password: wktjmmafhonbxkjn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      group-id: notificacao-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: kafka:9092

client:
  cadastro-usuarios-service:
    name: cadastro-usuarios-service-client
    url: ${CADASTRO_USUARIO_SERVICE_HOST:http://localhost:8080}/api/auth
    api-key: RXN0YSDDqSBhIGFwaS1rZXkgZG8gYXR1dGVudGljYcOnw6NvLXNlcnZpY2U=

server:
  port: 8083